routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get( '/',  ['as' => 'welcome',      'uses' => 'WelcomeController@show']);

// Login routes
Route::get( 'login',  ['as' => 'login',      'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login',  ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
Route::post('logout', ['as' => 'logout',     'uses' => 'Auth\LoginController@logout']);

// Registration Routes
Route::get( 'register',  ['as' => 'register',      'uses' => 'Auth\RegisterController@showRegistrationForm']);
Route::post('register',  ['as' => 'register.post', 'uses' => 'Auth\RegisterController@register']);


Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function ()
{
    Route::group(['prefix' => 'facebook', 'namespace' => 'Facebook'], function ()
    {
        Route::get('login',    ['as' => 'auth.facebook.login',    'uses' => 'AuthController@redirectToProvider']);
        Route::get('callback', ['as' => 'auth.facebook.callback', 'uses' => 'AuthController@handleProviderCallback']);
    });
});

Route::group(['middleware' => 'auth'], function() {
    Route::resource('products', 'ProductsController');

    Route::group(['prefix' => 'prelandings'], function() {
        Route::get('/{prelanding}/preview', ['as' => 'prelandings.preview', 'uses' => 'PrelandingsController@preview']);
    });

    Route::group(['prefix' => 'landings'], function() {
        Route::get('/{landing}/preview', ['as' => 'landings.preview', 'uses' => 'LandingsController@preview']);
    });

    Route::group(['prefix' => 'campaings'], function() {
        Route::post('/store',            ['as' => 'campaigns.store',  'uses' => 'CampaignsController@store']);
        Route::put( '{campaign}/update', ['as' => 'campaigns.update', 'uses' => 'CampaignsController@update']);
    });

    Route::get('dashboard',           ['as' => 'dashboard.show',     'uses' => 'DashboardController@show']);
    Route::get('dashboard/data',      ['as' => 'dashboard.get.data', 'uses' => 'DashboardController@getAjaxForMainChart']);

    Route::get('statistics',          ['as' => 'statistics.show',     'uses' => 'StatisticsController@show']);
    Route::get('statistics/download', ['as' => 'statistics.download', 'uses' => 'StatisticsController@download']);

    Route::group(['prefix' => 'payouts'], function() {
        Route::get( '/',               ['as' => 'payouts.index', 'uses' => 'PayoutRequestsController@index']);
        Route::post('create',          ['as' => 'payout.store',  'uses' => 'PayoutRequestsController@store']);
        Route::put( '{payout}/cancel', ['as' => 'payout.cancel', 'uses' => 'PayoutRequestsController@cancel']);
    });

    Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'namespace' => 'Admin'], function() {
        Route::get( '/', ['as' => 'admin', 'uses' => 'AdminController@index']);

        Route::resource('users',       'UsersController',       ['as' => 'admin']);
        Route::resource('products',    'ProductsController',    ['as' => 'admin']);
        Route::resource('landings',    'LandingsController',    ['as' => 'admin']);
        Route::resource('countries',   'CountriesController',   ['as' => 'admin']);
        Route::resource('campaigns',   'CampaignsController',   ['as' => 'admin']);
        Route::resource('prelandings', 'PrelandingsController', ['as' => 'admin']);
        Route::resource('prelandings', 'PrelandingsController', ['as' => 'admin']);
    });
});

Route::get('tracking/{uuid}',                   ['as' => 'campaigns.render.prelanding', 'uses' => 'CampaignsRenderController@renderPrelanding']);
Route::get('tracking/{uuid}/landing/{landing}', ['as' => 'campaigns.render.landing',    'uses' => 'CampaignsRenderController@renderLanding']);
Route::get('iframe/{uuid}',                     ['as' => 'campaigns.iframe.render',     'uses' => 'CampaignsRenderController@renderIframe']);
Route::get('details',                           ['as' => 'campaigns.details',           'uses' => 'CampaignsRenderController@getDetails']);

resources/views/parts/footer.blade.php
<div id="footer">
    Copyright 2017 Network Affliate, <a href="">Privacy Policy</a> | <a href="">Terms and Conditions </a>
</div>

resources/views/parts/navbar.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#app-navbar-collapse">
                <span class="sr-only">Toggle Navigation</span> <span class="icon-bar"></span>
                <span class="icon-bar"></span> <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name') }}
            </a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <!-- Left Side Of Navbar -->
            <ul class="nav navbar-nav">
                @if (Auth::check())
                    <li><a href="{{ route('dashboard.show') }}"><i class="fa fa-tachometer" aria-hidden="true"></i>&nbsp;Dashboard</a>
                    </li>
                    <li><a href="{{ route('products.index') }}"><i class="fa fa-list" aria-hidden="true"></i>&nbsp;Offers</a>
                    </li>
                    <li><a href="{{ route('statistics.show') }}"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;Statistics</a>
                    </li>
                    <li><a href="{{  route('payouts.index') }}"><i class="fa fa-bar-chart" aria-hidden="true"></i>&nbsp;Payout</a>
                    </li>

                    @can('admin', Auth::user())
                        <li><a href="{{ route('admin') }}">Admin</a></li>
                    @endcan
                @endif
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                <!-- Authentication Links -->
                @if (Auth::guest())

                    <li><a href="{{ route('login') }}">Login</a></li>
                    <li><a href="{{ route('register') }}">Register</a></li>
                @else
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a id="logout" href="#" data-href="{{ route('logout') }}">
                                <i class="fa fa-sign-out" aria-hidden="true"></i>Logout
                            </a>
                        </li>
                        <li><a href="#">Edit profile data</a></li>

                    </ul>
                @endif
            </ul>
        </div>
    </div>
</nav>